// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20230420090103_withsession")]
    partial class withsession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedLibrary.Models.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromPlanetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HeroMapId")
                        .HasColumnType("int");

                    b.Property<Guid?>("SessionMapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToPlanetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HeroMapId");

                    b.HasIndex("SessionMapId");

                    b.ToTable("Edge");
                });

            modelBuilder.Entity("SharedLibrary.Models.Hero", b =>
                {
                    b.Property<int>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroId"));

                    b.Property<int>("Argb")
                        .HasColumnType("int");

                    b.Property<byte>("ColonizationShipLimit")
                        .HasColumnType("tinyint");

                    b.Property<int>("HeroMapId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ResearchShipLimit")
                        .HasColumnType("tinyint");

                    b.Property<int>("Resourses")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HeroId");

                    b.HasIndex("HeroMapId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("SharedLibrary.Models.HeroMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<Guid>("HomePlanetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomePlanetId");

                    b.ToTable("HeroMapViews");
                });

            modelBuilder.Entity("SharedLibrary.Models.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HeroMapId")
                        .HasColumnType("int");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionMapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HeroMapId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SessionMapId");

                    b.ToTable("Planet");
                });

            modelBuilder.Entity("SharedLibrary.Models.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("SharedLibrary.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionMapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionMapId")
                        .IsUnique();

                    b.ToTable("Session");
                });

            modelBuilder.Entity("SharedLibrary.Models.SessionMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("SessionMaps");
                });

            modelBuilder.Entity("SharedLibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharedLibrary.Models.Edge", b =>
                {
                    b.HasOne("SharedLibrary.Models.HeroMap", null)
                        .WithMany("Connections")
                        .HasForeignKey("HeroMapId");

                    b.HasOne("SharedLibrary.Models.SessionMap", null)
                        .WithMany("Connections")
                        .HasForeignKey("SessionMapId");
                });

            modelBuilder.Entity("SharedLibrary.Models.Hero", b =>
                {
                    b.HasOne("SharedLibrary.Models.HeroMap", "HeroMap")
                        .WithOne("Hero")
                        .HasForeignKey("SharedLibrary.Models.Hero", "HeroMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Models.Session", "Session")
                        .WithMany("Heroes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Models.User", "User")
                        .WithMany("Heroes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroMap");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Models.HeroMap", b =>
                {
                    b.HasOne("SharedLibrary.Models.Planet", "HomePlanet")
                        .WithMany()
                        .HasForeignKey("HomePlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomePlanet");
                });

            modelBuilder.Entity("SharedLibrary.Models.Planet", b =>
                {
                    b.HasOne("SharedLibrary.Models.HeroMap", null)
                        .WithMany("Planets")
                        .HasForeignKey("HeroMapId");

                    b.HasOne("SharedLibrary.Models.Point", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Models.SessionMap", null)
                        .WithMany("Planets")
                        .HasForeignKey("SessionMapId");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SharedLibrary.Models.Session", b =>
                {
                    b.HasOne("SharedLibrary.Models.SessionMap", "SessionMap")
                        .WithOne("Session")
                        .HasForeignKey("SharedLibrary.Models.Session", "SessionMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionMap");
                });

            modelBuilder.Entity("SharedLibrary.Models.SessionMap", b =>
                {
                    b.HasOne("SharedLibrary.Models.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SharedLibrary.Models.HeroMap", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Hero");

                    b.Navigation("Planets");
                });

            modelBuilder.Entity("SharedLibrary.Models.Session", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("SharedLibrary.Models.SessionMap", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Planets");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SharedLibrary.Models.User", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
